=head1 NAME

mod_ts ("modify timestamp") walks (recursively) through directories and changes the 
timestamp of each directory to the newest contained entry.

=head1 DESCRIPTION

this program lets you change the timestamps of directories depending on their 
contained entries.

for each directory the timestamp will be changed to the newest contained file 
or directory.

=head1 MOVED

moved to gitlab: https://gitlab.com/wp-seth/mod_ts
